/**:
  ros__parameters:
    serial_port: "/dev/ttyUSB0"
    baudrate: 115200
    vel_topic: "vel"
    rpm_scale: 25.0 # gear ratio and direction
    max_vel: 3500.0 # max rpm set in controller

    # For querying data from the motor controller
    frequency: 50   #higher frequency (value is in ms)
    query:
      motor_amps : ?A
      motor_command : ?M
      # hall_count : ?Cb
      # hall_speed : ?BS
      # volts : ?V
      # feedback : ?F 
      # battery_amps : ?BA
      # power : ?P          
      # fault_flag : ?FF  
      # motor_amps2 : ?MA
      # motor_command2 : ?FM
      # hall_count2 : ?FM
      # hall_speed2 : ?FS
      # volts2 : ?V
      # feedback2 : ?rmp 
      # battery_amps2 : ?PHA
      # power2 : ?sns          
      fault_flag2 : ?FF 
      status_flag : ?FS
      # firmware_id : ?FID  
      # encoder_count : ?C
      encoder_speed : ?S  
